---
sudo: false

language:
  - php
  - node_js

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

install:
  - bash bin/install-wp-tests.sh wordpress wordpress_test root '' localhost $WP_VERSION

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - composer install
  - export WP_CORE_DIR=/tmp/wordpress
  - php /tmp/wp-cli.phar server --path=$WP_CORE_DIR > /dev/null 2>/dev/null &
  - sleep 5
  - ln -s $TRAVIS_BUILD_DIR $WP_CORE_DIR/wp-content/plugins/
  - php /tmp/wp-cli.phar plugin activate $(basename $TRAVIS_BUILD_DIR) --path=$WP_CORE_DIR
  - php /tmp/wp-cli.phar selenium start --path=$WP_CORE_DIR
  - sleep 5

script:
  - php /tmp/wp-cli.phar codeception run --debug --path=$WP_CORE_DIR
